<a href="https://colab.research.google.com/github/samiltanveer1999/Python-Practice-in-Google-Colab/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Practice Problems of Numpy

In [4]:
import numpy as np
import sympy as sp
from IPython.display import display

#create a 2D matrix
matrix1 = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])


matrix2 = sp.Matrix(
    #matrix brackets
    [
        #rows
        [8,9],
        [10,11],
        [13,14]

    ]

)

print("numpy matrix: ","\n",matrix1, "\n"*3)
print("sympy matrix: ")
display(matrix2)


#create a 5x5 zero matrix & a 2x3 one matrix
zero_matrix = np.zeros((5,5))
one_matrix = np.ones((2,3))
print("\n"*3,"Zero matrix: ", "\n",zero_matrix, "\n"*3)
print("one matrix: ", "\n",one_matrix, "\n"*3)

print("Shape Checking  \n")
print("zero_matrix shape: ", zero_matrix.shape)
print("one_matrix shape:", one_matrix.shape, "\n"*3)




#creating column and row vector

column1 = np.array([
    [1],
    [2],
    [3],
    [4]
]

)

row1 = np.array(
    [
        [1, 2, 3, 4]
    ]
)

print("column vector:", column1, "\n"*3, "row vector:", row1)








numpy matrix:  
 [[1 2]
 [3 4]
 [5 6]] 



sympy matrix: 


Matrix([
[ 8,  9],
[10, 11],
[13, 14]])




 Zero matrix:  
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 



one matrix:  
 [[1. 1. 1.]
 [1. 1. 1.]] 



Shape Checking  

zero_matrix shape:  (5, 5)
one_matrix shape: (2, 3) 



column vector: [[1]
 [2]
 [3]
 [4]] 


 row vector: [[1 2 3 4]]


# **Vectorized** **Operations**

In [ ]:
#Matrix Multiplication

import numpy as np

K = np.array(
    [
        [2, -1],
        [-1, 2]
    ]
)

u = np.array(
    [
        [1],
        [3]
    ]
)


#Element wise multiplication:
print("Elemet multiplication: K * u  \n", K*u, "\n"*3)

#Matrix Multiplication:
print("Matrix multiplication: K@u \n", K@u, "\n"*3) #or np.dot(K, u)




#Solving Matrix Equation with np.linalg.solve : the equation is K2. u2 = F

K2 = np.array(
    [
        [4, -1, 0],
        [-1, 4, -1],
        [0, -1, 3]
    ]
)

F = np.array(
    [
        [15],
        [10],
        [10]
    ]
)


#k2 @ u2 = F

u2 = np.linalg.solve(K2, F)

print(f"The solution of displacement is:\n\n", u2, "\n"*3)













Elemet multiplication: K * u  
 [[ 2 -1]
 [-3  6]] 



Matrix multiplication: K@u 
 [[-1]
 [ 5]] 



The solution of displacement is:

 [[5.]
 [5.]
 [5.]] 





# **Eigen Values And Eigen Vectors:**
a matrix A can have many (eigenvalue, eigenvector) pairs.
A square matrix of size $n \times n$ will have exactly $n$ eigenvalues, and each one will have at least one corresponding eigenvector

In [ ]:
import numpy as np


Matrix_A = np.array(
    [
        [2, -1, 0],
        [-1, 2, -1],
        [0, -1, 2]
    ]
)


lamda_A, v_A = np.linalg.eig(Matrix_A)

lamda_1 = lamda_A[0]
v_1 = v_A[:, 0]

print(f"lamda_1 * v_1: \n {lamda_1 * v_1}")
print(f"\n Matrix_A * v_1 : \n {np.dot(Matrix_A, v_1)}")




lamda_1 * v_1: 
 [-1.70710678  2.41421356 -1.70710678]

 Matrix_A * v_1 : 
 [-1.70710678  2.41421356 -1.70710678]
